name: Run grit patterns test

env:
  GRIT_TELEMETRY_DISABLED: "true"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [ubuntu-22.04, nscloud-ubuntu-22.04-amd64-4x16]
        node-version: [16.16, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2

      - name: install grit
        run: curl -fsSL https://docs.grit.io/install | bash

      - name: Run doctor
        run: grit doctor

      - name: Run grit patterns test
        run: grit patterns test
